# Generated by Django 4.1.2 on 2022-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('youtube_video__isnull', False), models.Q(
                ('pdf_file__exact', ''), _negated=True), _connector='OR'), name='video-or-pdf'),
        ),
    ]
