# Generated by Django 4.1.2 on 2022-10-15 09:33

import courses.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(upload_to='exams', validators=[courses.validators.PDFFileValidator(max_size=52428800)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(check=models.Q(('related_course__isnull', False), ('category__isnull', False), _connector='OR'), name='course_or_category'),
        ),
    ]
