# Generated by Django 4.1.2 on 2022-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_exam_exam_course_or_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
