# Generated by Django 4.1.2 on 2022-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_exam_categories_alter_exam_related_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, to='courses.category'),
        ),
    ]
