# Generated by Django 4.1.6 on 2023-02-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_category_course_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
